ui: form-field checkbox-group key renamed to avoid run-time warning
Fixes run-time warning
DOMException: Failed to execute 'querySelector' on 'Document'
because key contains a stringified map whose special characters are a
problem for react.